lang: ru-RU
number-sections: true
toc: false
execute:
  enabled: false
crossref:
  fig-title: Рисунок
  tbl-title: Таблица
format:
  docx:
    reference-doc: reference.docx
    highlight-style: tango
    fig-width: 6.1
    fig-height: 3.6
