project:
  title: "Лабораторная работа № 1"
  output-dir: "_output"

lang: ru-RU
format:
  revealjs:
    embed-resources: true
    slide-number: true
    transition: fade
    background-transition: fade
    width: 1280
    height: 720
    margin: 0.08
    center: false
    controls: true
    progress: true
    css: styles.css
